export {default as Quran} from './Quran/Quran'
export {default as PrayerTimes} from './PrayerTimes/PrayerTimes'
export {default as About} from './About/About'
export {default as Contact} from './Contact/Contact'
export {default as Projects} from './Projects/Projects'
export {default as SignIn} from './SignIn/SignIn'
export {default as SignUp} from './SignUp/SignUp'
export {default as Profile} from './Profile/Profile'