export {default as Header} from './Header/Header'
export {default as Footer} from './Footer/Footer'
export {default as Colors} from './Colros/Colors'
export {default as QuranLecture} from './QuranLecture/QuranLecture'
export {default as QuranLive} from './QuranLive/QuranLive'
export {default as Time} from './Time/Time'
export {default as CardPrayer} from './CardPrayer/CardPrayer'
export {default as Loading} from './Loading/Loading'